### PR TITLE
Seed for coach

### LINKED ISSUE #40: Seed coach profiles
Generate profiles to fill out the coach listing page (https://lichess.org/coach)

Can be done in a similar way to #30

### PR DESCRIPTION
**Pull request by Carbrex**
Hey, this is my attempt for seeding of coach profiles. I used [this](https://github.com/lichess-org/lila/blob/master/modules/coach/src/main/Coach.scala) module from lichess/lila and [this](https://github.com/lichess-org/lila-db-seed/pull/30) Pr from @fitztrev . Can you help me how to run and check the code?
Closes #40

### CODE REVIEW

**Comment by fitztrev** [comment]
Thanks for the PR.

You'll also need to register the argument like this:

https://github.com/lichess-org/lila-db-seed/blob/751353637af75a70072b6af84bd2bb83080c4c58/spamdb/modules/args.py#L139-L146

**Comment by fitztrev** [comment]
For testing it, if you use lila-gitpod, you can checkout your PR in the `repos/lila-db-seed` folder then if you modify the [`lila-docker` file and add `--coaches`](https://github.com/lichess-org/lila-docker/blob/c48f512758b1ce4f586289348924f6d2d8209a40/lila-docker#L61), you can run `./lila-docker db` to test the seeder.

**Comment by Carbrex** [comment]
> Thanks for the PR.
> 
> You'll also need to register the argument like this:
> 
> https://github.com/lichess-org/lila-db-seed/blob/751353637af75a70072b6af84bd2bb83080c4c58/spamdb/modules/args.py#L139-L146

Ok thanks. I didnt see that in the pr so I had no idea about it.


> For testing it, if you use lila-gitpod, you can checkout your PR in the `repos/lila-db-seed` folder then if you modify the [`lila-docker` file and add `--coaches`](https://github.com/lichess-org/lila-docker/blob/c48f512758b1ce4f586289348924f6d2d8209a40/lila-docker#L61), you can run `./lila-docker db` to test the seeder.

Yes, I use lila-docker. I think it will be same for that.

**Comment by Carbrex** [comment]
Hey, I ran `./lila-docker db` and I can see the coaches in the db but I don't see any coaches on the `/coach` route. Is there a way I can create a coach using predefined functions so that I can check what did I miss. The page in `/coach` has a way to apply for coach but I guess that won't be the right way because it redirects to a google form. Thanks for your time!

**Comment by fitztrev** [comment]
Yes, I think if you do this:

1. log in as admin
2. go to a profile of a titled player (may not be necessary to be titled, but the coaches on Lichess are so might as well)
3. go to mod view of that user
4. change their permissions - there should be a toggle switch of "is a coach"
5. log in as that user, you should now be able to edit your coach profile

**Comment by Carbrex** [comment]
> Yes, I think if you do this:
> 
> 1. log in as admin
> 2. go to a profile of a titled player (may not be necessary to be titled, but the coaches on Lichess are so might as well)
> 3. go to mod view of that user
> 4. change their permissions - there should be a toggle switch of "is a coach"
> 5. log in as that user, you should now be able to edit your coach profile

Thanks! that helped.

**Comment by Carbrex** [comment]
`/coach` page
image
`/coach/{user}` page
image

**Comment by fitztrev** [comment]
Thanks!

**Pull request merged**
